### ISSUE TITLE
Cluster/Server Hardening

### ISSUE THREAD

**Issue by moorepants** [LibreTexts/metalc#12]
Go through best practices at setting up a secure cluster and server(s) setup.

- [ ] Review https://github.com/imthenachoman/How-To-Secure-A-Linux-Server and determine which things we should implement.
  - [x] Set maximum authorization attempts to 6
  - [x] Turned off password authentication, can only log in with public key
      - [x] Ask Richard if no passwords is ok
  - [x] Removed short Diffie-Hellman keys
  - [x]  Setup Network Time Protocol(NTP) for keeping system time in sync.
  - [x] Set up AllowGroups (Did NOT do this due to the # of accounts we already have on the server)
  - [x] Securing /proc. (Did NOT do this due to # of accounts)
  - [x] Added a more secure entropy pool
  - [x] Cleaned up UFW rules
  - [x] Installed psad (with some disabled features as said below)
  - [x] Installed unattended-upgrades
  - [x] Installed fail2ban
  - [x] Installed AIDE
  - [ ] ~~Maybe change the SSH port~~ Moved to #58 
  - [ ] ~~Contain PSAD, improve the functionality of it~~ Moved to https://github.com/LibreTexts/metalc/issues/56
  - [ ] ~~Secure password in SSH~~ We already moved to signing in with a public key instead of a password.
  - [x] Installed rkhunter and chrootkit to detect rootkits
- [ ] ~~Make sure that we have control groups or something similar set up so that you can't crash a node the way we were able to in the past.~~ We believe that since Kubernetes already tracks the capacity, it will not schedule new pods if the pods will cause the node to go over the limits the node scheduler will not schedule them on that node: https://kubernetes.io/docs/concepts/architecture/nodes/#node-capacity
- [x] We'll want to have a list of things to monitor to ensure that the cluster is functioning so we can put them into a monitoring system so we are alerted if the system goes offline.
  - [x] Setup basic alerts for the cluster, alerts are sent via Slack and Email when:
    - [x] jupyter.libretexts.org goes down.
    - [x] Ping is too high for jupyter.libretexts.org .
    - [x] The cluster CPU/cores/RAM utilization exceeds 80%.
    - [x] Single node CPU/RAM utilization exceeds 90%.
    - [x] If a node goes down/offline.
- [ ] ~~Is HAproxy setup so that there are multiple containers providing at least the main front page for Jupyterlab?~~ Moved/mentioned in https://github.com/LibreTexts/metalc/issues/34
- [x] Setup a cronjob to automatically install ubuntu 18.04 security updates, see #4

**Comment by celine168** [comment]
We changed the password to the server.

**Comment by moorepants** [comment]
Ok, I haven't posted my key yet. Can you add this to the server: 

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDG1RKTxPK5C25en6L9koKF6JPKSLBi8phH4YSYhVyYWMd/QV/bbes9EFyeyAO5E3x3FqRXH62w+dHzAOvBVHDeIx+9wwoa66hMMh+WPlN6r7H2fceNll5A4y0gK6Ne/JOYDhW29FZmGs8NE8YkyUfABuAeR5925zasHDDazVGxt9wM2V433PIhRyyakSGtCwmnTwPhPSvXRX6/Be6foTiFa4RAQDeewv9oUgKxPCc4gF0xmKQBgFcu9IYMqi0qfxe7ZwVxH9WNUhuthdBRx8bPgyq6GhGpScF4/pOisJbEBwI4605F5VrU7NFCOhxBDvELwpJxj3YeC6jmH0pUxuND moorepants@gmail.com
```

**Comment by lux12337** [comment]
I have added your key to the authorized users, please try to login if you have time.

**Comment by moorepants** [comment]
I can log in with my rsa key.

**Comment by moorepants** [comment]
At today's meeting @lux12337 and @celine168 agreed to create a list of the primary server hardening issues that need to be taken care of for the production launch milestone.

**Comment by celine168** [comment]
**Going through *How to Secure a Linux Server***:
* Set maximum authorization attempts to 6
* Turned off password authentication, can only log in with public key
* Removed short Diffie-Hellman keys

We did NOT:
* set up 2FA
* set up AllowGroups (due to the accounts we already have on the server)

**Comment by moorepants** [comment]
I moved these items in the list at the top, feel free to edit that directly.

**Comment by celine168** [comment]
We chose not to set up AllowGroups or secure /proc since there is only one account on the server. In future, will there be more accounts to access rooster, or should we assume that there is only one account to access rooster in the future?

**Comment by moorepants** [comment]
We may have more accounts on rooster, but don't worry about that for now. No on the 2FA is fine. I'm not a big fan of it anyways. I'll delete those from the list at the top.

**Comment by moorepants** [comment]
@celine168 Make sure all these things you do end up in the documentation files too. (if you aren't already doing that)

**Comment by lux12337** [comment]
I have changed the credentials to login to Grafana and have stored them in our secret metalc-configuration repo.

**Comment by celine168** [comment]
I updated the documentation, will still be implementing a few more things

**Comment by lux12337** [comment]
By Dean's suggestions, I have added a redundant power supply unit to both rooster and chick0(the master node), to safeguard the cluster in the event of a power supply unit failure. In the future, we would ideally have a redundant power supply unit for each one of the nodes as well, preferably on a separate power strip.

**Comment by moorepants** [comment]
Sounds great. Are the extra power supplies something we need to purchase?

**Comment by lux12337** [comment]
No, every chick has a second power supply ready, they just haven't been plugged in yet. We just need more power cables. Richard is coming back next week, I'll ask him for more cables.

**Comment by celine168** [comment]
I ran the [Lynis security audit](https://github.com/imthenachoman/How-To-Secure-A-Linux-Server#lynis---linux-security-auditing) and received a hardening index of 68. Will need take the audit's security suggestions into account.

**Comment by moorepants** [comment]
Open up separate issues for any hanging items in this one and close this issue. @lux12337 agreed to do this, I believe.

**Comment by celine168** [comment]
I have moved the remaining open topics to new or existing issues. Closing this issue in favor of those above.
