### ISSUE TITLE
Add a page that shows all the team members

### ISSUE THREAD

**Issue by moorepants** [LibreTexts/metalc#55]
It would be nice to have an "about" page, like jupyter.libretexts.org/about that told a bit about what we are doing and why and showed headshots of the team (past and present).

- [x] Jason needs to write the about page text

**Comment by celine168** [comment]
Documentation on this:
https://github.com/LibreTexts/jupyterhub-templates
https://github.com/LibreTexts/jupyterhub-images

**Comment by moorepants** [comment]
We discussed using a modal or section on the same page so that we don't have to add a new html page.

**Comment by narrator0** [comment]
@moorepants Can you list all the people that need to be included?

**Comment by moorepants** [comment]
Current: Luigi, Celine, Hao, Tannavee, Richard, Jason

Past: Kevin Krausse, Xiaochen Zeng

**Comment by narrator0** [comment]
Just did more research and found out that we are only able to customize pages before the user enters Jupyter Notebook which probably no one will see the link or button we added. If we want to customize the Notebook, we might need a custom spawner which I don't think will worth the time researching at this point.

My suggestion is that we create a page on https://mechmotum.github.io/ and add some links on JupyterHub. What do you think?

**Comment by moorepants** [comment]
I just want this on the front page before your login.

**Comment by narrator0** [comment]
Got it. I will add an about section on the bottom of the login page.

**Comment by narrator0** [comment]
As discussed on Monday(11/28), we will move the about page to its own page as well as the faqs.

## todos

- [ ] create new about page
- [ ] create new faq page
- [ ] clean up current login page
- [ ] add link to the two page on the current navbar
- [ ] add beta on the current navbar

**Comment by moorepants** [comment]
- name each target community: libretexts and ucd
- explain with couple sentences what each community is
- dual support for education and research
- education through research through hands on computing
- a team of students and faculty started in feb 2019
- mention finding support (both grant and 
- pioneering of this type of service/resource for learners and researchers
- cross disciplinary: supporting data science, computing for cross disciplines
- foundation and broad set of of open source software tools in many languages

**Comment by narrator0** [comment]
@moorepants what title should I put under you, Richard, and all of us?

**Comment by moorepants** [comment]
You all are "Site Reliability Engineering Assistants". I am "Assistant Professor of Teaching". Look on the bioinformatics website for richard's title.

**Comment by moorepants** [comment]
@tkumar98  Is there any about text drafted yet?

**Comment by tkumar98** [comment]
As part of a pioneering initiative at UC Davis, this JupyterHub equips LibreTexts instructors and their students, as well as UC Davis faculty, staff, and students. Since LibreTexts has grown to being one of the largest open access textbook websites, this JupyterHub complements the plethora of educational texts available by providing the resources for learning through hands-on computing. Additionally, collaboration with the UC Davis Bioinformatics Core has made possible a dynamic and flexible environment that provides dual support for education and research. The groundwork for the foundation that has been built is through a broad set of open source software tools in many languages. Furthermore, given the ever-fluctuating changes and requirements when it comes to research, this JupyterHub brings forth a cross-disciplinary approach by allowing for powerful data analysis and computing to take place. Such a resource would not be possible without the expertise of students and faculty that began the project in February 2019 through grant support and collaboration with LibreTexts and the UC Davis Genome Center.

**Comment by tkumar98** [comment]
Please let me know if anything needs to be changed

**Comment by moorepants** [comment]
Looks good. Have @narrator0 put it in his PR!

**Comment by tkumar98** [comment]
@narrator0 it's good to go, please add it to the intro section

**Comment by narrator0** [comment]
@moorepants All the pages are ready. I created two PRs ready to merge:

* https://github.com/LibreTexts/jupyterhub-templates/pull/4
* https://github.com/LibreTexts/jupyterhub-images/pull/1

Do I need someone to review before I merge or should I just merge them?

**Comment by moorepants** [comment]
At least 1 person should review each person before merging.

**Comment by narrator0** [comment]
Ok. Will find someone to review and merge after. I will also deploy it to staging after they are merged.

**Comment by narrator0** [comment]
Deployed to production. Closing the issue.

**Comment by moorepants** [comment]
Excellent!
