### ISSUE TITLE
Implement Jupyter Enabled LibreTexts pages

### ISSUE THREAD

**Issue by moorepants** [LibreTexts/metalc#86]
Here is a summary of the desired features:

- [x] The author interface needs to be simple (having to write complex html tags is not necessarily ideal and there needs to be a clear connection to the code you write and what is displayed)
- [x] Needs common IDE features:
  - [x] cell by cell line execution
  - [x] clear indication of code execution errors
  - [x] syntax highlighting
- [x] Needs to support many open source languages
- [x] We need ipywidgets to work so that students can work with the widget in addition to or other than the code to manipulate a visualization,plots,table,etc.
- [x] Students need to be able to make plots with the various languages and plotting libraries for those languages.
- [x] Needs the ability to hide the code from students (i.e. author develops the code for a specific static or interactive plot and students don't see the code).
- [x] We need all images to display as soon as the reader arrives on the page (without have to run any code cells).

Secondary:
- [ ] We need all widgets to display as soon as the reader arrives on the page (without have to run any code cells).
- IDE stuff:
  - [ ] display linting errors
  - [ ] autocompletion
- Add a "wait until kernel is finished flag" until the kernel is done running (indicate when code is running or done running)

- Users need to be able to add non-standard packages to the computing environment (see #85) (medium priority)

# Task list

- [x] Summarize the differences between thebelab and juniper.
- [x] Choose to implement thebelab or juniper.
- [x] Research on how we can add custom CKeditor plugin to Mindtouch
- [x] Setup Repo to develop the CKeditor plugin (must include local and production setup)
- [x] Split task into small tickets
- [x] Develop integration JS code (CKeditor plugin) to implement thebelab

# Other

See this summary of the survey results for more details:

https://docs.google.com/document/d/1eV08l_4djKJ7bc8r0LPbD5bp3QT7mHTZgABUleH15H0/edit?usp=sharing

**Comment by moorepants** [comment]
Note that this issue may need to be broken up into sub-issues once we start to understand all the pieces of getting this working.

**Comment by moorepants** [comment]
There is a new project "voila" https://twitter.com/maartenbreddels/status/1192537101545476097?s=20 that does cool stuff with widgets. It should be checked out to see if it could be useful to us.

**Comment by celine168** [comment]
Voila looks pretty awesome! We'll look into it. 
About the page load time: I realized we can add a function to make the Jupyter kernel load automatically when a page is loaded (aka the "Activate" button on Thebelab gets 'clicked' automatically).
```
<p><button id="activateButton" style="width: 150px; height: 75px; font-size: 1.5em;">Activate</button><script>/*<![CDATA[*/
var bootstrapThebe = function() {
    thebelab.bootstrap();
}
<pre data-executable="true" data-language="python">
print("Hello!")</pre>
<script type="text/javascript">/*<![CDATA[*/
function codeAddress() {
   bootstrapThebe();
}
window.onload = codeAddress;
/*]]>*/</script>
```

**Comment by moorepants** [comment]
Can someone do task 1 first:  Summarize the differences between thebelab and juniper.

**Comment by celine168** [comment]
## Thebelab
* Thebelab has the optional Activate button, used to turn static code blocks into executable ones
* More support the Juniper (more commits to the repo)

## Juniper
* Run button is in top right kernel
* Seems like there's not much support on Juniper; only 15 commits on the repo

Both offer editable, executable code blocks.

**Comment by moorepants** [comment]
Some comments:

- I don't understand the difference in "activate" and "run", is it that you have to activate and then press run on thebelab and only press run on juniper? Would the latter be better? What's the point of activating?
- The # of commits is the whole story. Does the projects have more commits lately? Does ti have more stars? Does it have more issues and pull requests being closed? Does it have upstream projects using it?
- What does it mean to "support isolated code blocks"?
- So both are 1 kernel per page, that sounds good and what we want.
- What makes it more apparent for the colorful code?
- Almost seems they are the same thing. Is that true?

**Comment by celine168** [comment]
> Needs the ability to hide the code from students (i.e. author develops the code for a specific static or interactive plot and students don't see the code).
Would it be okay to hide the code beneath a dropdown link (in other words, we hide it be default if the author wants to, and the code would show if the reader clicks on the link to dropdown the code?)

* In Thebelab, there's an option to show the code blocks as non-runnable blocks (like basically like text boxes) until you click an "Activate" button.
* Thebelab's most recent commit is 6 days ago. Juniper's most recent commit was in April.
* Both have a similar number of stars: Thebelab has 103 stars, while Juniper has 123 stars.
* "support isolated code blocks" refers to supporting separating code blocks into different kernels.
* Thebelab's colors for their code blocks is less saturated, if that makes sense. At first glance it could look completely black.
* Both are very similar. As far as I know, Thebelab seems to offer more features. Juniper is based off of Thebelab. 

I hope this clears things up a bit.

**Comment by moorepants** [comment]
We are choosing thebelab and going to contribute some of the niceties of juniper back to thebelab.

**Comment by moorepants** [comment]
We talked about the "simplest author interface" today. That is, that we would like a single button press (or keyboard shortcut) to insert a code block (pre or code html tag). And then a single button to make the page "jupyter enabled" or not. With those two things we should be able to make the page work with our binder via thebelab. We want to avoid the templates and having to dig through the menu to find that embedjupyter option.

**Comment by narrator0** [comment]
Just to document how we can load a plugin to the MindTouch CKeditor.

## Plugin Register

Plugin must be registered right after `editor.js` is loaded and before initializing any instances of CKeditor. Currently, I loaded the script in the footer (which is not the correct way to do it. somewhere in the header might be more proper).

## Plugin Initialize

The plugin UI button must be registered when initialized. I added this via `config.toolbar` in the system setting section. The settings here will be ran when initializing a new instance of CKeditor.

**Comment by narrator0** [comment]
New repo created for developing the CKeditor plugin to integrate Binder and Libretexts at https://github.com/LibreTexts/ckeditor-binder-plugin.
